name: Integration Test - Terraform (All)

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  CICD-integration-test:
    name: CICD Integration Test
    uses: ./.github/workflows/tf-cicd-integration-test-main.yml
    secrets: inherit
